### ISSUE TITLE
retrieve.py format error

### ISSUE THREAD

**Issue by CoderOverflow** [vinayakkailas/Face_Recognition#6]
I cannot start the service due to the weird codings in retrieve.py

![7 1 s tn7qtzl zqmmh](https://user-images.githubusercontent.com/29338660/49124851-e86bf300-f2f8-11e8-83a3-4290087ab401.png)

**Comment by CoderOverflow** [comment]
After modify the indent of this piece of codes, it works
![image](https://user-images.githubusercontent.com/29338660/49125616-94aed900-f2fb-11e8-9c8d-a93fde9573a0.png)

**Comment by vinayak-parab** [comment]
Hello @CoderOverflow Can you please shre how you indented tge actual code in the oython file? I am getting an indentation error.
