### ISSUE TITLE
what's the meaning of parameter K in identify_person function in retrieve.py?

### ISSUE THREAD

**Issue by CoderOverflow** [vinayakkailas/Face_Recognition#8]
def identify_person(image_vector, feature_array, k=9):

top_k_ind = np.argsort([np.linalg.norm(image_vector-pred_row) for ith_row, pred_row in enumerate(feature_array.values())])[:k]

what's the meaning of parameter K in identify_person function in retrieve.py?

**Comment by jadhavsaurabh** [comment]
may be nearest k nearest neighbours K
